### PR TITLE
Created modding system

### PR DESCRIPTION
**Pull request by Pololot64**
Made the mapgen a mod, made biomes mods, made a mod loader. Other improvements and less hardcoding

_~MintFan aka Pololot64_

### CODE REVIEW

**Comment by archfan7411** [comment]
I approve this PR, good work 👍 

Just one thing: CLRF file endings (an empty newline at the end of the file) is common coding practice and is sometimes (though rarely) required by badly designed systems. But this is an issue of code style and isn't required :)

Will merge once Pie gives his approval.

**Comment by piecubed** [comment]
Unnecessary comments, but looks good.  Which file gets run on start now?

**Comment by archfan7411** [comment]
No such thing as "Unnecessary comments" ;)
I think ModLoader is run first now.

**Comment by Pololot64** [comment]
The file attached to World. Modloader.gd

**Comment by piecubed** [comment]
# yawn mintfan too tired to program

**Comment by piecubed** [comment]
Hehe

**Comment by piecubed** [comment]
Ill delete them later

**Comment by Pololot64** [comment]
lol sure

**Pull request merged**
